// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	analysis "golang.org/x/tools/go/analysis"
)

// DB is an autogenerated mock type for the DB type
type DB struct {
	//mock.Mock
}

// Get provides a mock function with given fields: key
func (_m *DB) Get(key string) (analysis.Analyzer, error) {return analysis.Analyzer{}, nil}

type mockConstructorTestingTNewDB interface {
	Cleanup(func())
}

// NewDB creates a new instance of DB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDB(t mockConstructorTestingTNewDB) *DB {
	mock := &DB{}
	return mock
}
